use strict; use warnings; use utf8; use Test::More; use File::Temp qw(tempfile); use JSON::PP;
my ($fh, $path) = tempfile(); binmode $fh, ':encoding(UTF-8)'; print $fh "Zoë: TODO café\n"; close $fh;
my $script = './this-could-have-been-a-regex.pl';
my $file = qx{$^X $script --json $path}; my $pipe = qx{printf 'Zoë: TODO café\\n' | $^X $script --json -};
my $a = decode_json($file); my $b = decode_json($pipe);
is_deeply $a, $b, 'UTF-8 file and stdin JSON agree';
is $a->{speakers}{'Zoë'}, 1, 'Unicode speaker survives CLI';
is_deeply $a->{actions}, ['café'], 'Unicode action survives CLI';
my $actions = qx{printf 'Ada: TODO send notes\nBob: ACTION call team\n' | $^X $script --actions-only -};
like $actions, qr/^line 1: - send notes/m, 'actions-only includes original line number'; like $actions, qr/^line 2: - call team/m, 'actions-only includes each action line';
my $speaker_json = qx{printf 'Ada: TODO send notes\nBob: ACTION call team\n' | $^X $script --json --speaker Ada -};
my $speaker_report = decode_json($speaker_json); is_deeply $speaker_report->{actions}, ['send notes'], 'speaker filter composes with JSON'; is $speaker_report->{action_lines}[0]{line}, 1, 'JSON action line preserves number';
my $unicode_speaker = qx{printf 'Zoë: TODO café\nBob: TODO nope\n' | $^X $script --json --speaker 'Zoë' -}; my $unicode_report = decode_json($unicode_speaker); is_deeply $unicode_report->{actions}, ['café'], 'Unicode speaker filter matches decoded label';
my $redacted_speaker = qx{printf 'a\@b.example: TODO call\n' | $^X $script --json --redact --speaker 'a\@b.example' -}; my $redacted_report = decode_json($redacted_speaker); is_deeply $redacted_report->{actions}, ['call'], 'speaker matches before redaction'; is $redacted_report->{speaker_filter}, '[speaker filter redacted]', 'redaction does not leak speaker filter';
my $empty_speaker_status = system("$^X $script --speaker '   ' - </dev/null >/dev/null 2>/dev/null"); isnt $empty_speaker_status, 0, 'whitespace-only speaker rejected';
my $long_speaker_status = system("$^X $script --speaker '" . ('x' x 41) . "' - </dev/null >/dev/null 2>/dev/null"); isnt $long_speaker_status, 0, 'overlong speaker rejected';
my ($limit_fh, $limit_path) = tempfile(); binmode $limit_fh, ':raw'; print $limit_fh 'a' x 1_048_576; close $limit_fh;
my $limit_report = decode_json(qx{$^X $script --json $limit_path}); is $limit_report->{lines}, 1, 'exact-limit input is accepted';
my $limit_pipe = decode_json(qx{cat "$limit_path" | $^X $script --json -}); is_deeply $limit_pipe, $limit_report, 'exact-limit file and stdin agree';
my ($over_fh, $over_path) = tempfile(); binmode $over_fh, ':raw'; print $over_fh 'a' x 1_048_577; close $over_fh;
my $over_status = system("$^X $script --json $over_path >/dev/null 2>/dev/null"); isnt $over_status, 0, 'over-limit file rejected';
my $over_pipe_status = system("cat '$over_path' | $^X $script --json - >/dev/null 2>/dev/null"); isnt $over_pipe_status, 0, 'over-limit stdin rejected';
my ($bad_fh, $bad_path) = tempfile(); binmode $bad_fh, ':raw'; print $bad_fh "\xff"; close $bad_fh;
my $bad_status = system("$^X $script --json $bad_path >/dev/null 2>/dev/null"); isnt $bad_status, 0, 'invalid UTF-8 rejected after bounded read';
unlink $limit_path, $over_path, $bad_path;
unlink $path; done_testing;
