use strict; use warnings; use utf8; use Test::More; use File::Temp qw(tempfile); use JSON::PP;
my ($fh, $path) = tempfile(); binmode $fh, ':encoding(UTF-8)'; print $fh "Zoë: TODO café\n"; close $fh;
my $script = './this-could-have-been-a-regex.pl';
my $file = qx{$^X $script --json $path}; my $pipe = qx{printf 'Zoë: TODO café\\n' | $^X $script --json -};
my $a = decode_json($file); my $b = decode_json($pipe);
is_deeply $a, $b, 'UTF-8 file and stdin JSON agree';
is $a->{speakers}{'Zoë'}, 1, 'Unicode speaker survives CLI';
is_deeply $a->{actions}, ['café'], 'Unicode action survives CLI';
my $actions = qx{printf 'Ada: TODO send notes\nBob: ACTION call team\n' | $^X $script --actions-only -};
like $actions, qr/^line 1: - send notes/m, 'actions-only includes original line number'; like $actions, qr/^line 2: - call team/m, 'actions-only includes each action line';
my $speaker_json = qx{printf 'Ada: TODO send notes\nBob: ACTION call team\n' | $^X $script --json --speaker Ada -};
my $speaker_report = decode_json($speaker_json); is_deeply $speaker_report->{actions}, ['send notes'], 'speaker filter composes with JSON'; is $speaker_report->{action_lines}[0]{line}, 1, 'JSON action line preserves number';
my $unicode_speaker = qx{printf 'Zoë: TODO café\nBob: TODO nope\n' | $^X $script --json --speaker 'Zoë' -}; my $unicode_report = decode_json($unicode_speaker); is_deeply $unicode_report->{actions}, ['café'], 'Unicode speaker filter matches decoded label';
my $redacted_speaker = qx{printf 'a\@b.example: TODO call\n' | $^X $script --json --redact --speaker 'a\@b.example' -}; my $redacted_report = decode_json($redacted_speaker); is_deeply $redacted_report->{actions}, ['call'], 'speaker matches before redaction'; is $redacted_report->{speaker_filter}, '[speaker filter redacted]', 'redaction does not leak speaker filter';
my $markdown = qx{printf 'A|B: TODO check [ship] `now` *today* &copy; ~~later~~\nZoë: ACTION café\n' | $^X $script --markdown -};
like $markdown, qr/^# Meeting handoff/m, 'markdown has handoff heading';
like $markdown, qr/A\\\|B/, 'markdown escapes speaker table pipe';
my $escaped_action = 'check \\[ship\\] \\`now\\` \\*today\\*';
ok index($markdown, $escaped_action) >= 0, 'markdown escapes checklist metacharacters';
like $markdown, qr/\\&copy; \\~\\~later\\~\\~/, 'markdown escapes entities and strikethrough markers';
like $markdown, qr/\_\(line 1\)\_/, 'markdown keeps original action line number';
ok index($markdown, 'line 1') < index($markdown, 'line 2'), 'markdown preserves action source order';
my $newline_markdown = qx{printf 'TODO: fold\rcontinuation\n' | $^X $script --markdown -};
like $newline_markdown, qr/fold continuation/, 'markdown normalizes embedded line breaks in action text';
my $dedupe_json = qx{printf 'Ada: TODO ship\nAda: ACTION ship\nBob: TODO ship\n' | $^X $script --json --dedupe-actions -};
my $dedupe_report = decode_json($dedupe_json); is scalar(@{$dedupe_report->{action_lines}}), 2, 'dedupe JSON collapses only within a speaker'; is_deeply $dedupe_report->{action_lines}[0]{lines}, [1, 2], 'dedupe JSON retains occurrence lines'; is $dedupe_report->{action_lines}[0]{count}, 2, 'dedupe JSON reports count';
my $dedupe_text = qx{printf 'Ada: TODO ship\nAda: ACTION ship\n' | $^X $script --actions-only --dedupe-actions -};
like $dedupe_text, qr/repeated on lines 1?2|repeated on lines 2; 2 occurrences/, 'dedupe text indicates repeated source';
my $dedupe_plain = qx{printf 'Ada: TODO ship\nAda: ACTION ship\n' | $^X $script --dedupe-actions -};
like $dedupe_plain, qr/actions \/ TODOs:\n  - ship \(repeated on lines 2; 2 occurrences\)/, 'normal text reports repeated source';
my $contains_json = qx{printf 'Zoë: TODO Ship [A+B]\nZoë: ACTION ship later\nAda: TODO unrelated\n' | $^X $script --json --contains 'a+b' --speaker 'Zoë' --dedupe-actions -};
my $contains_report = decode_json($contains_json); is_deeply $contains_report->{actions}, ['Ship [A+B]'], 'contains is literal and composes with speaker/dedupe';
my $secret_contains = qx{printf 'Ada: TODO email a\@b.example\n' | $^X $script --json --redact --contains 'a\@b.example' -}; my $secret_contains_report = decode_json($secret_contains); is $secret_contains_report->{contains}, '[search filter redacted]', 'redaction does not leak contains filter'; unlike $secret_contains, qr/a\@b\.example/, 'redacted JSON output omits raw contains value';
my $csv = qx{printf 'Ada: TODO quote, "now"\nZoë: ACTION café\nAda: TODO quote, "now"\n' | $^X $script --csv --dedupe-actions -};
like $csv, qr/^line,speaker,text,count,lines\r?\n/, 'csv has fixed header'; like $csv, qr/"1","Ada","quote, ""now""","2","1;3"\r?\n/, 'csv quotes commas and quotes and retains dedupe lines'; like $csv, qr/"2","Zo.+","caf.+","1","2"\r?\n/, 'csv preserves Unicode and source order';
my $csv_status = system("$^X $script --csv --json - </dev/null >/dev/null 2>/dev/null"); isnt $csv_status, 0, 'csv and json are mutually exclusive';
my $window_json = qx{printf 'Ada: TODO one\nBob: TODO two\nAda: TODO three\n' | $^X $script --json --lines 2:3 -}; my $window_report = decode_json($window_json); is_deeply $window_report->{actions}, ['two', 'three'], 'line window composes with JSON'; is $window_report->{lines}, 3, 'line window JSON retains full input count';
my $window_bad = system("$^X $script --lines 3:2 - </dev/null >/dev/null 2>/dev/null"); isnt $window_bad, 0, 'reversed line window rejected';
my $window_malformed = system("$^X $script --lines 0:x - </dev/null >/dev/null 2>/dev/null"); isnt $window_malformed, 0, 'malformed line window rejected';
my $window_exact = system("$^X $script --lines 1000000:1000000 - </dev/null >/dev/null 2>/dev/null"); is $window_exact, 0, 'one-million line endpoint accepted';
my $window_over = system("$^X $script --lines 1000001:1000001 - </dev/null >/dev/null 2>/dev/null"); isnt $window_over, 0, 'line endpoint over one million rejected';
my $contains_bad = system("$^X $script --contains '' - </dev/null >/dev/null 2>/dev/null"); isnt $contains_bad, 0, 'empty contains rejected';
my $contains_long = system("$^X $script --contains '" . ('x' x 201) . "' - </dev/null >/dev/null 2>/dev/null"); isnt $contains_long, 0, 'overlong contains rejected';
my $filtered_markdown = qx{printf 'Ada: TODO a\@b.example\nZoë: TODO keep [this]\n' | $^X $script --markdown --actions-only --speaker 'Zoë' --redact -};
like $filtered_markdown, qr/^## Action checklist/m, 'markdown actions-only has checklist'; unlike $filtered_markdown, qr/\*\*Lines:\*\*/, 'markdown actions-only suppresses summary counts'; unlike $filtered_markdown, qr/a\@b\.example/, 'markdown speaker filter excludes other speakers'; ok index($filtered_markdown, 'keep \\[this\\]') >= 0, 'markdown composes speaker filter and redaction';
my $both_status = system("$^X $script --json --markdown - </dev/null >/dev/null 2>/dev/null"); isnt $both_status, 0, 'json and markdown are mutually exclusive';
my $empty_speaker_status = system("$^X $script --speaker '   ' - </dev/null >/dev/null 2>/dev/null"); isnt $empty_speaker_status, 0, 'whitespace-only speaker rejected';
my $long_speaker_status = system("$^X $script --speaker '" . ('x' x 41) . "' - </dev/null >/dev/null 2>/dev/null"); isnt $long_speaker_status, 0, 'overlong speaker rejected';
my ($limit_fh, $limit_path) = tempfile(); binmode $limit_fh, ':raw'; print $limit_fh 'a' x 1_048_576; close $limit_fh;
my $limit_report = decode_json(qx{$^X $script --json $limit_path}); is $limit_report->{lines}, 1, 'exact-limit input is accepted';
my $limit_pipe = decode_json(qx{cat "$limit_path" | $^X $script --json -}); is_deeply $limit_pipe, $limit_report, 'exact-limit file and stdin agree';
my ($over_fh, $over_path) = tempfile(); binmode $over_fh, ':raw'; print $over_fh 'a' x 1_048_577; close $over_fh;
my $over_status = system("$^X $script --json $over_path >/dev/null 2>/dev/null"); isnt $over_status, 0, 'over-limit file rejected';
my $over_pipe_status = system("cat '$over_path' | $^X $script --json - >/dev/null 2>/dev/null"); isnt $over_pipe_status, 0, 'over-limit stdin rejected';
my ($bad_fh, $bad_path) = tempfile(); binmode $bad_fh, ':raw'; print $bad_fh "\xff"; close $bad_fh;
my $bad_status = system("$^X $script --json $bad_path >/dev/null 2>/dev/null"); isnt $bad_status, 0, 'invalid UTF-8 rejected after bounded read';
unlink $limit_path, $over_path, $bad_path;
unlink $path; done_testing;
