use strict;
use warnings;
use utf8;
use Test::More;
require './this-could-have-been-a-regex.pl';
my $r = main::summarize("Ada: TODO send notes\nBob: sounds good\nACTION: book room\n", 0);
is $r->{lines}, 3, 'line count'; is $r->{words}, 10, 'word count'; is_deeply $r->{speakers}, { Ada => 1, Bob => 1 }, 'speaker lines'; is_deeply $r->{actions}, ['send notes', 'book room'], 'actions';
is main::summarize('', 0)->{words}, 0, 'empty input';
ok main::summarize("Zoë: café\n", 0)->{words} == 2, 'unicode words';
my $p = main::summarize('Mail me a@b.example or call 555-123-4567', 1); like $p->{actions}[0] // '', qr/^/, 'no crash'; ok $p->{redacted}, 'redaction marker';
my $filtered = main::summarize("Ada: TODO send notes\nBob: ACTION call team\nTODO: open doc\n", 0, 'Ada');
is_deeply $filtered->{actions}, ['send notes'], 'speaker filter keeps matching actions'; is $filtered->{speakers}{Ada}, 1, 'speaker filter keeps matching speaker'; ok !exists $filtered->{speakers}{Bob}, 'speaker filter excludes other speaker'; is $filtered->{action_lines}[0]{line}, 1, 'action keeps original line number';
my $copy = main::summarize("Ada: TODO send notes\n", 0); $copy->{action_lines}[0]{text} = 'changed'; is_deeply $copy->{actions}, ['send notes'], 'action text and action line are independent';
my $redacted_action = main::summarize("Ada: TODO email a\@b.example or call 555-123-4567\n", 1, 'Ada'); like $redacted_action->{actions}[0], qr/email redacted.*phone redacted/, 'redaction composes with speaker action extraction';
my $deduped = main::summarize("Ada: TODO ship\nAda: ACTION ship\nBob: TODO ship\nTODO: ship\nTODO: ship\n", 0, undef, 1);
is_deeply $deduped->{actions}, ['ship', 'ship', 'ship', 'ship'], 'dedupe keeps one action per speaker and unlabelled occurrences separate';
is_deeply $deduped->{action_lines}[0]{lines}, [1, 2], 'dedupe retains all matching source lines'; is $deduped->{action_lines}[0]{count}, 2, 'dedupe records occurrence count'; is $deduped->{action_lines}[1]{speaker}, 'Bob', 'dedupe preserves distinct speaker';
my $redaction_collision = main::summarize("Ada: TODO email a\@b.example\nBob: TODO email a\@b.example\n", 1, undef, 1);
is scalar(@{$redaction_collision->{action_lines}}), 2, 'redaction collision does not merge different speakers';
my $nul_collision = main::summarize("A\0B: TODO C\nA: TODO B\0C\n", 0, undef, 1);
is scalar(@{$nul_collision->{action_lines}}), 2, 'embedded NULs cannot collide in dedupe key';
my $contained = main::summarize("Zoë: TODO Ship café [A+B]\nAda: TODO ship later\n", 0, undef, 0, 'CAFÉ');
is_deeply $contained->{actions}, ['Ship café [A+B]'], 'contains filter is case-insensitive and literal';
my $oversized_error = eval { main::summarize('x' x 1_048_577, 0); 1 }; ok !$oversized_error && $@ =~ /exceeds/, 'direct summarize enforces byte bound';
done_testing;
